### ISSUE TITLE
Misc issues with PPSSPP debugger integration

### ISSUE THREAD

**Issue by kotcrab** [kotcrab/ghidra-allegrex#15]
- `Target is already being recorded` when transitioning between stepping and running states. Needs investigating, could be an issue in Ghidra. 
    - See https://github.com/NationalSecurityAgency/ghidra/discussions/3559
  - `Current frame's bank does not exist` when clicking through stack frames, PPSSPP doesn't expose such information. Some workaround needed, maybe we just need to provide an empty register bank
  - Step out error is ignored  - e.g. when there is no more stack frames. Ghidra steps are async so not much can be done about this, it just might be confusing to the user
  - Can't trigger breakpoint hit events - will be available thanks to https://github.com/hrydgard/ppsspp/pull/15051

**Comment by sajattack** [comment]
Any plans for psplink/gdbserver integration?

**Comment by Nemoumbra** [comment]
So... As of August 2, 2023...

1) It's probably still a Ghidra issue (I couldn't find if this was fixed in the Ghidra repo), but apparently there's a workaround: we need to uncheck "Record Automatically" and hit "Record" after we've launched to prevent the error from popping up.
2) Saving *all* the register values in *all* stack frames by PPSSPP is very expensive and we can't effectively figure the values out all the time via stack walking due to our register-based calling convention. Does the plugin provide the empty bank right now?
3) Why doesn't the async code produce any error messages?
4) Has this been implemented? I suggest kotcrab to edit the message ~accordingly~ if that's completed.

**Comment by kotcrab** [comment]
There wasn't really any changes to the integration since this issue was created so those points still stand.

> Why doesn't the async code produce any error messages?

I think the issue was with there being no way to deliver the unsuccessful step out event to the Ghidra but not sure.

**Comment by kotcrab** [comment]
I'm going to close this one. Ghidra is replacing the debugger API with a new, incompatible one so there isn't any point in trying to improve this integration. I'll be removing it when they fully stop supporting it (or when it breaks enough).
