### ISSUE TITLE
Allegrex plugin does not import some retail games that have debug symbols.

### ISSUE THREAD

**Issue by SylvieWrath** [kotcrab/ghidra-allegrex#9]
![image](https://user-images.githubusercontent.com/88959271/131611721-a97833f2-3404-466a-a823-905488c20821.png)
This happened earlier when i tried to important Adventure Player. Can't seem to recreate for some reason, but i'm still getting similar, but smaller, error messages when i try to import most games with what I'm told are "unstripped binaries":

![image](https://user-images.githubusercontent.com/88959271/131612119-0917dd19-1aa7-436a-8553-46350bc72963.png)
![image](https://user-images.githubusercontent.com/88959271/131612368-69cf625a-e772-43a4-ad3e-e09e4f58f48e.png)
![image](https://user-images.githubusercontent.com/88959271/131612504-339e012a-bb66-43a0-b57d-7a1a57b8349a.png)
![image](https://user-images.githubusercontent.com/88959271/131612544-206d1922-41cd-4d67-b798-1af0156b5eb4.png)
Happens for:
-Armored Core
-Adventure Player
-Big Bang Bang
-Demo Disc
-Astonishia
-Puzzle Bobble
-Glorace
-Rengoku
-Sampler

THREE EXCEPTIONS THOUGH: It manages to import Yu Gi Oh, Jan, and Jikan successfully, but they spit out some "Additional Information"

![image](https://user-images.githubusercontent.com/88959271/131612285-982a4dc6-2880-4bee-9f44-2c3448006bb1.png)
![image](https://user-images.githubusercontent.com/88959271/131612665-4bfd5321-881a-4b00-b187-bb85fc6c24dd.png)
![image](https://user-images.githubusercontent.com/88959271/131612727-2ac47ce1-9f18-4652-80b5-17163737e685.png)

**Comment by kotcrab** [comment]
These binaries contain few relocation sections in normal MIPS format. I'm pretty sure those can be ignored as they are only related to debugging so that's what I did. If anyone can provide some info what's their use we can reconsider this.

Weird thing about symbols: Ghidra can create arrays instead of dissembling functions, easily fixed by clearing the array and rerunning analysis.

> but they spit out some "Additional Information"

Those `Skipping section` messages can usually be ignored. The only weird thing is invalid `.bss` section. I looked at that file with `readelf` and sure enough `.bss` size is 0 even though it's clearly used
```
[24] .bss              NOBITS          000dd420 0dd474 000000 01  WA  0   0 128
```
This can be fixed manually in Memory Map by manually creating `.bss`. (might need to remove `EXTERNAL` block in case of conflict) I'm guessing its size can be determined from program headers (use `readelf` etc.). This should be done before any analysis is done.

**Comment by John-K** [comment]
Do you know what sort of data those sections contain? Symbol data is of particular interest as it can be used to generate a function id database to apply to other binaries that do not have symbols.

**Comment by kotcrab** [comment]
Do you mean sections that can't be relocated? I don't but I'm guessing it's nothing useful, some misc stuff related to debugging:
![javaw_2021-09-01_20-30-33](https://user-images.githubusercontent.com/4594081/131724977-e51005e3-9cf1-4766-9128-5fa7edbfd985.png)
Ghidra only analyzes `debug_frame` by itself looks like.

**Comment by sajattack** [comment]
I think it's usually .debug and .debug_str that have the info needed for the fidb, but I could be wrong.
